from src.blueprints.ui import (
    ui_auth_bp,
    ui_dashboard_bp,
    ui_schedule_bp,
    ui_apparmor_bp,
    ui_spa_bp,
)
from src.blueprints.api import (
    api_devices_bp,
    api_users_bp,
    api_schedule_bp,
    api_blocklists_bp,
    api_time_bp,
    api_tasks_bp,
    api_alerts_bp,
    api_pairing_bp,
    api_dashboard_bp,
    api_installed_apps_bp,
    api_approvals_bp,
    api_android_device_policy_bp,
    api_linux_device_policy_bp,
    api_nintendo_bp,
    api_xbox_bp,
    api_screenshots_bp,
    api_youtube_bp,
)
from src.blueprints.api_access_requests import bp as api_access_requests_bp
from src.blueprints.websocket import websocket_bp

__all__ = [
    'ui_auth_bp',
    'ui_dashboard_bp',
    'ui_schedule_bp',
    'ui_apparmor_bp',
    'ui_spa_bp',
    'api_devices_bp',
    'api_users_bp',
    'api_schedule_bp',
    'api_blocklists_bp',
    'api_time_bp',
    'api_tasks_bp',
    'api_alerts_bp',
    'api_pairing_bp',
    'api_dashboard_bp',
    'api_installed_apps_bp',
    'api_approvals_bp',
    'api_android_device_policy_bp',
    'api_linux_device_policy_bp',
    'api_nintendo_bp',
    'api_xbox_bp',
    'api_screenshots_bp',
    'api_youtube_bp',
    'api_access_requests_bp',
    'websocket_bp',
]
