"""Add WebHistory table

Revision ID: 121e8f860952
Revises: l3g8h9i0j1k2
Create Date: 2026-06-16 14:06:21.618895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121e8f860952'
down_revision = 'l3g8h9i0j1k2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('device_id', sa.String(length=50), nullable=False),
        sa.Column('managed_user_id', sa.Integer(), nullable=False),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('domain', sa.String(length=255), nullable=False),
        sa.Column('visited_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['device_id'], ['agent_device.system_id'], ),
        sa.ForeignKeyConstraint(['managed_user_id'], ['managed_user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_history', schema=None) as batch_op:
        batch_op.create_index('web_history_user_visited_idx', ['managed_user_id', 'visited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_history', schema=None) as batch_op:
        batch_op.drop_index('web_history_user_visited_idx')

    op.drop_table('web_history')
    # ### end Alembic commands ###
