"""add marketplace fields

Revision ID: 66fd98cac85c
Revises: m4h9i0j1k2l3
Create Date: 2026-06-18 14:22:35.064876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66fd98cac85c'
down_revision = 'm4h9i0j1k2l3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocklist_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_marketplace', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('preset_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocklist_source', schema=None) as batch_op:
        batch_op.drop_column('preset_id')
        batch_op.drop_column('is_marketplace')

    # ### end Alembic commands ###
