"""empty message

Revision ID: 6f4e9d1f9b34
Revises: 512784c28f0f
Create Date: 2026-06-07 00:00:45.003314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4e9d1f9b34'
down_revision = '512784c28f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapping_android_device_policy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block_nfc', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapping_android_device_policy', schema=None) as batch_op:
        batch_op.drop_column('block_nfc')

    # ### end Alembic commands ###
