"""add app policies

Revision ID: 79742a0e8bb5
Revises: 97e5991a96f2
Create Date: 2026-05-28 16:47:20.588002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79742a0e8bb5'
down_revision = '97e5991a96f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_policy_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.String(length=120), nullable=False),
    sa.Column('executable_path', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=32), nullable=False),
    sa.Column('preset', sa.String(length=32), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['app_policy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'executable_path', name='apparmor_policy_rule_exec_uc')
    )
    op.create_table('managed_user_app_policy_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('managed_user_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['managed_user_id'], ['managed_user.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['app_policy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('managed_user_id', 'policy_id', name='managed_user_app_policy_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('managed_user_app_policy_assignment')
    op.drop_table('app_policy_rule')
    op.drop_table('app_policy')
    # ### end Alembic commands ###
