"""add linux_users_json to agent_device

Revision ID: 7c66dbe66fa1
Revises: 79742a0e8bb5
Create Date: 2026-05-28 21:35:35.910526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c66dbe66fa1'
down_revision = '79742a0e8bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linux_users_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_device', schema=None) as batch_op:
        batch_op.drop_column('linux_users_json')

    # ### end Alembic commands ###
