"""Initial schema

Revision ID: 97e5991a96f2
Revises: 
Create Date: 2026-05-28 00:38:53.279833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e5991a96f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_device',
    sa.Column('system_id', sa.String(length=50), nullable=False),
    sa.Column('system_hostname', sa.String(length=255), nullable=True),
    sa.Column('system_ip', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('secure_token', sa.String(length=64), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_table('blocklist_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=32), nullable=False),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('source_last_modified', sa.String(length=255), nullable=True),
    sa.Column('content_revision', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('agent_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('linux_username', sa.String(length=80), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('webhook_enabled_snapshot', sa.Boolean(), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('last_delivery_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_delivery_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['agent_device.system_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocklist_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['blocklist_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'domain', name='blocklist_source_domain_uc')
    )
    op.create_table('managed_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('system_id', sa.String(length=50), nullable=True),
    sa.Column('system_ip', sa.String(length=50), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_config', sa.Text(), nullable=True),
    sa.Column('pending_time_adjustment', sa.Integer(), nullable=True),
    sa.Column('pending_time_operation', sa.String(length=1), nullable=True),
    sa.Column('daily_limit_adjustment_date', sa.Date(), nullable=True),
    sa.Column('daily_limit_adjustment_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['agent_device.system_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managed_user_blocklist_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('managed_user_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['managed_user_id'], ['managed_user.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['blocklist_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('managed_user_id', 'source_id', name='managed_user_blocklist_uc')
    )
    op.create_table('managed_user_device_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('managed_user_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(length=50), nullable=False),
    sa.Column('linux_username', sa.String(length=50), nullable=False),
    sa.Column('linux_uid', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_config', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocklist_policy_hash', sa.String(length=64), nullable=True),
    sa.Column('blocklist_is_synced', sa.Boolean(), nullable=False),
    sa.Column('blocklist_last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocklist_last_attempted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocklist_last_attempt_hash', sa.String(length=64), nullable=True),
    sa.Column('blocklist_last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['managed_user_id'], ['managed_user.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['agent_device.system_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('managed_user_id', 'system_id', name='managed_user_system_uc'),
    sa.UniqueConstraint('system_id', 'linux_uid', name='system_linux_uid_uc'),
    sa.UniqueConstraint('system_id', 'linux_username', name='system_linux_username_uc')
    )
    op.create_table('user_daily_time_interval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=True),
    sa.Column('end_hour', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['managed_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day_of_week', 'sort_order', name='user_day_interval_sort_order_uc')
    )
    op.create_table('user_time_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['managed_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='user_date_uc')
    )
    op.create_table('user_weekly_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monday_hours', sa.Float(), nullable=True),
    sa.Column('tuesday_hours', sa.Float(), nullable=True),
    sa.Column('wednesday_hours', sa.Float(), nullable=True),
    sa.Column('thursday_hours', sa.Float(), nullable=True),
    sa.Column('friday_hours', sa.Float(), nullable=True),
    sa.Column('saturday_hours', sa.Float(), nullable=True),
    sa.Column('sunday_hours', sa.Float(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['managed_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_usage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_map_id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.String(length=120), nullable=False),
    sa.Column('executable_path', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_map_id'], ['managed_user_device_map.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apparmor_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_map_id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.String(length=120), nullable=False),
    sa.Column('executable_path', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=32), nullable=False),
    sa.Column('preset', sa.String(length=32), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_map_id'], ['managed_user_device_map.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_map_id', 'executable_path', name='apparmor_device_map_exec_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apparmor_rule')
    op.drop_table('app_usage_history')
    op.drop_table('user_weekly_schedule')
    op.drop_table('user_time_usage')
    op.drop_table('user_daily_time_interval')
    op.drop_table('managed_user_device_map')
    op.drop_table('managed_user_blocklist_assignment')
    op.drop_table('managed_user')
    op.drop_table('blocklist_domain')
    op.drop_table('agent_alert')
    op.drop_table('settings')
    op.drop_table('blocklist_source')
    op.drop_table('agent_device')
    # ### end Alembic commands ###
