"""Add android_force_installed_app table

Revision ID: c1aa5a072532
Revises: 5402dcba67b7
Create Date: 2026-06-08 10:23:48.289832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1aa5a072532'
down_revision = '5402dcba67b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'android_force_installed_app',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('system_id', sa.String(length=50), nullable=False),
        sa.Column('package_name', sa.String(length=255), nullable=False),
        sa.Column('apk_url', sa.Text(), nullable=False),
        sa.Column('sha256_checksum', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['system_id'], ['mapping_android_device_policy.system_id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('system_id', 'package_name', name='android_force_installed_app_package_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('android_force_installed_app')
    # ### end Alembic commands ###

