"""Add AI policy and logging tables

Revision ID: f1576ce83951
Revises: t0p5q6r7s8t9
Create Date: 2026-06-25 13:29:19.130102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1576ce83951'
down_revision = 't0p5q6r7s8t9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapping_approval_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_policy_mode', sa.String(length=32), nullable=False, server_default='off'))
        batch_op.add_column(sa.Column('ai_prompt_logging', sa.String(length=32), nullable=False, server_default='metadata_only'))
        batch_op.add_column(sa.Column('ai_daily_time_limit', sa.Integer(), nullable=True))

    op.create_table(
        'ai_prompt_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('device_map_id', sa.Integer(), nullable=False),
        sa.Column('service', sa.String(length=64), nullable=False),
        sa.Column('domain', sa.String(length=128), nullable=False),
        sa.Column('prompt_text', sa.Text(), nullable=True),
        sa.Column('prompt_length', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(length=1024), nullable=False),
        sa.Column('title', sa.String(length=256), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['device_map_id'], ['managed_user_device_map.id'], name='fk_ai_prompt_log_device_map'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ai_prompt_log_map_idx', 'ai_prompt_log', ['device_map_id', 'logged_at'], unique=False)

    op.create_table(
        'ai_session_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('device_map_id', sa.Integer(), nullable=False),
        sa.Column('domain', sa.String(length=128), nullable=False),
        sa.Column('duration_seconds', sa.Integer(), nullable=False),
        sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['device_map_id'], ['managed_user_device_map.id'], name='fk_ai_session_log_device_map'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ai_session_log_map_idx', 'ai_session_log', ['device_map_id', 'logged_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ai_session_log_map_idx', table_name='ai_session_log')
    op.drop_table('ai_session_log')
    op.drop_index('ai_prompt_log_map_idx', table_name='ai_prompt_log')
    op.drop_table('ai_prompt_log')

    with op.batch_alter_table('mapping_approval_settings', schema=None) as batch_op:
        batch_op.drop_column('ai_daily_time_limit')
        batch_op.drop_column('ai_prompt_logging')
        batch_op.drop_column('ai_policy_mode')
    # ### end Alembic commands ###
